# Uncomment this line to define a global platform for your project

platform :ios, ‘7.0’

target 'I_NScreen' do
pod 'AFNetworking+streaming', '~> 0.6.2’
pod 'Realm', '~> 0.94’
pod 'CocoaLumberjack', '~> 2.0'
pod 'Reachability', '~> 3.2'
pod 'ZipArchive', '~> 1.4'
pod 'GDataXML-HTML', '~> 1.2'
pod 'SIAlertView', '~> 1.3'

end

target 'I_NScreenTests' do

end

